version: '2'
services:
    medstat-app:
        image: medstat
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://medstat-postgresql:5432/medStat
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://medstat-elasticsearch:9200
        ports:
            - 8080:8080
    medstat-postgresql:
        extends:
            file: postgresql.yml
            service: medstat-postgresql
    medstat-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: medstat-elasticsearch
